import { type Candidate } from "./types";

export const mockCandidates: Candidate[] = [
  {
    id: "1",
    name: "Name Surname",
    position: "Position",
    status: "New",
    rating: 0,
    linkedin: "#",
    github: "#",
    resume: "#",
    phone: "+48 000 000 000",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  {
    id: "2",
    name: "Name Surname",
    position: "Data Engineer",
    status: "New",
    rating: 1,
    github: "#",
    resume: "#",
    email: "maila@mail.com",
    note: "Note about the candidate, truncated...",
    dateAdded: "Yesterday",
    activityLevel: "recent",
  },
  {
    id: "3",
    name: "Name Surname",
    position: "Data Engineer",
    status: "Reviewed",
    rating: 4,
    linkedin: "#",
    github: "#",
    email: "maila@mail.com",
    dateAdded: "Monday",
    activityLevel: "normal",
  },
  {
    id: "4",
    name: "Name Surname",
    position: "Data Engineer",
    status: "1st Call",
    rating: 3,
    linkedin: "#",
    resume: "#",
    phone: "+48 000 000 000",
    email: "maila@mail.com",
    dateAdded: "Feb 28",
    activityLevel: "hot",
    hasCalendarEvent: true,
  },
  {
    id: "5",
    name: "Name Surname",
    position: "Data Engineer",
    status: "2nd Call",
    rating: 5,
    linkedin: "#",
    github: "#",
    resume: "#",
    phone: "+48 000 000 000",
    email: "maila@longmaila...",
    note: "Note about the candidate, truncated...",
    dateAdded: "Dec 1, 2025",
    activityLevel: "hot",
    hasCalendarEvent: true,
  },
  {
    id: "6",
    name: "Name Surname",
    position: "Data Engineer",
    status: "Deal",
    rating: 4,
    linkedin: "#",
    github: "#",
    email: "maila@mail.com",
    dateAdded: "Monday",
    activityLevel: "recent",
  },
  {
    id: "7",
    name: "Name Surname",
    position: "Data Engineer",
    status: "Hired",
    rating: 5,
    linkedin: "#",
    github: "#",
    email: "maila@mail.com",
    dateAdded: "Monday",
    activityLevel: "recent",
  },
  {
    id: "8",
    name: "Name Surname",
    position: "Data Engineer",
    status: "Rejected",
    rating: 3,
    linkedin: "#",
    github: "#",
    email: "maila@mail.com",
    dateAdded: "Monday",
    activityLevel: "normal",
  },
  {
    id: "9",
    name: "Name Surname",
    position: "Data Engineer",
    status: "Rejected",
    rating: 3,
    linkedin: "#",
    github: "#",
    phone: "+48 000 000 000",
    email: "maila@mail.com",
    dateAdded: "Monday",
    activityLevel: "normal",
  },
];

// Extended data for kanban view — multiple cards per column
export const mockKanbanCandidates: Candidate[] = [
  // New
  {
    id: "k1",
    name: "Name Surname",
    position: "Position",
    status: "New",
    rating: 0,
    github: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
    note: "Note about the candidate, truncated to 3 lines, note about the candidate...",
  },
  {
    id: "k2",
    name: "Name Surname",
    position: "Position",
    status: "New",
    rating: 0,
    github: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  {
    id: "k3",
    name: "Name Surname",
    position: "Position",
    status: "New",
    rating: 0,
    github: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  {
    id: "k4",
    name: "Name Surname",
    position: "Position",
    status: "New",
    rating: 0,
    github: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  // Reviewed
  {
    id: "k5",
    name: "Name Surname",
    position: "Position",
    status: "Reviewed",
    rating: 3,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  {
    id: "k6",
    name: "Name Surname",
    position: "Position",
    status: "Reviewed",
    rating: 4,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    note: "Note about the candidate, truncated to 3 lines, note about the candidate...",
    dateAdded: "Feb 28",
    activityLevel: "hot",
  },
  // 1st Call
  {
    id: "k7",
    name: "Name Surname",
    position: "Position",
    status: "1st Call",
    rating: 4,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  {
    id: "k8",
    name: "Name Surname",
    position: "Position",
    status: "1st Call",
    rating: 5,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    note: "Note about the candidate, truncated to 3 lines, note about the candidate...",
    dateAdded: "Feb 28",
    activityLevel: "hot",
    hasCalendarEvent: true,
  },
  // 2nd Call
  {
    id: "k9",
    name: "Name Surname",
    position: "Position",
    status: "2nd Call",
    rating: 0,
    linkedin: "#",
    github: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "Feb 28",
    activityLevel: "hot",
    hasCalendarEvent: true,
  },
  {
    id: "k10",
    name: "Name Surname",
    position: "Position",
    status: "2nd Call",
    rating: 0,
    linkedin: "#",
    github: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
    note: "Note about the candidate, truncated to 3 lines, note about the candidate...",
  },
  {
    id: "k11",
    name: "Name Surname",
    position: "Position",
    status: "2nd Call",
    rating: 0,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  {
    id: "k12",
    name: "Name Surname",
    position: "Position",
    status: "2nd Call",
    rating: 0,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  // Deal
  {
    id: "k13",
    name: "Name Surname",
    position: "Position",
    status: "Deal",
    rating: 4,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  {
    id: "k14",
    name: "Name Surname",
    position: "Position",
    status: "Deal",
    rating: 4,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "Feb 28",
    activityLevel: "hot",
    note: "Note about the candidate, truncated to 3 lines, note about the candidate...",
  },
  {
    id: "k15",
    name: "Name Surname",
    position: "Position",
    status: "Deal",
    rating: 4,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "Feb 28",
    activityLevel: "hot",
  },
  // Hired
  {
    id: "k16",
    name: "Name Surname",
    position: "Position",
    status: "Hired",
    rating: 4,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  {
    id: "k17",
    name: "Name Surname",
    position: "Position",
    status: "Hired",
    rating: 4,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  // Rejected
  {
    id: "k18",
    name: "Name Surname",
    position: "Position",
    status: "Rejected",
    rating: 0,
    linkedin: "#",
    github: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
  {
    id: "k19",
    name: "Name Surname",
    position: "Position",
    status: "Rejected",
    rating: 4,
    github: "#",
    linkedin: "#",
    resume: "#",
    email: "maila@mail.com",
    dateAdded: "2 min ago",
    activityLevel: "recent",
  },
];
